name: Deploy to Prod
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
