name: Deploy to Prod
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.TESTE }}
      EC2_URL: 'ec2-54-90-104-90.compute-1.amazonaws.com'
      EC2_USERNAME: 'ec2-user'
    runs-on: self-hosted
    steps:
      - name: SETUP MAVEN
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: CLEAN
        run: mvn clean
      - name: BUILD
        run: mvn package
      - name: COPY
        run: |
          rm -f docker/app.jar
          cp ./target/cervejaria-acme-0.0.1-SNAPSHOT.jar ./docker/app.jar

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
      - name: Print Secret
        run: echo "My secret is ${{ secrets.TESTE }}"
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'leogloriainfnet'
          password: 'dckr_pat_A7SM5cSJP50vRqg-baxVkU_s43w'
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: leogloriainfnet/cervejaria-acme:linux-latest