name: Deploy to Prod
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.TESTE }}
      EC2_URL: 'ec2-54-90-104-90.compute-1.amazonaws.com'
      EC2_USERNAME: 'ec2-user'
    runs-on: self-hosted
    steps:

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
      - name: Print Secret
        run: echo "My secret is ${{ secrets.TESTE }}"
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'leogloriainfnet'
          password: 'dckr_pat_A7SM5cSJP50vRqg-baxVkU_s43w'
